# OpenShift 411 override values

operators:
#  codeready-workspaces: # undefine

  devspaces:
    enabled: true
    namespace: openshift-operators
    subscription:
      channel: stable
      approval: Automatic
      operatorName: devspaces
      sourceName: redhat-operators
      sourceNamespace: openshift-marketplace
    operatorgroup:
      create: false
